[package]
name = "dep_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-lock = { version = "9.0.0", features = ["dependency-tree"] }
tame-index = { version = "0.9.1", features = ["sparse"] }
cargo_metadata = "0.18.1"
petgraph = "0.6.4"

basic_usages = { path = "../basic_usages" }
