[package]
name = "basic_usages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
fxhash = "0.2.1"
lazy_static = "1.4.0"
postgres = "0.19.7"
semver = "1.0.0"
